Cloudnative smf and amf integration test fixes
omec-project/smf pull request #126
Opened 2022-11-22 16:28 UTC by vthiruveedula

2022-11-25 03:50 UTC, thakurajayL requested changes

2022-11-25 03:50 UTC, thakurajayL commented on context/db.go
> +		fmt.Println("StoreSeidContextInDB, result string : ", ref)
No need to have this Println.

2022-11-25 03:50 UTC, thakurajayL commented on context/db.go
> +	}
Error case you should have log.

2022-11-25 03:50 UTC, thakurajayL commented on pfcp/adapter/adapter.go
> +func HandleAdapterPfcpRsp(pfcpMsg pfcp.Message, evtData *pfcpUdp.PfcpEventData) error {
Comment at start..why we don't need lock on upf in this function. Assumption is that this is synchronous call and called is already holding the upf lock ?

2022-11-25 03:50 UTC, thakurajayL commented on pfcp/adapter/adapter.go
> +		smContext.SubPfcpLog.Infof("in adt HandlePfcpSessionEstablishmentResponse rsp.UPFSEID.Seid [%v] ", rsp.UPFSEID.Seid)
what is "adt" in this log ?

2023-01-03 09:57 UTC, UpadhyayaAnkur submitted a review, later dismissed

2023-01-03 14:34 UTC, ajaythakurintel requested changes

2023-01-03 14:34 UTC, ajaythakurintel commented on context/db.go
> +	if result != nil {
Can you take care of the warning above ?

2023-01-03 14:34 UTC, ajaythakurintel commented on context/db.go
> +		fmt.Println("DB entry doesn't exist with seid: ", seid)
remove print.

2023-01-03 14:34 UTC, ajaythakurintel commented on context/db.go
> +		fmt.Println("DB entry doesn't exist with seid: ", seid)
remove print.

2023-01-03 14:34 UTC, ajaythakurintel commented on pfcp/adapter/adapter.go
> -	smContext.SubPfcpLog.Infof("in adt HandlePfcpSessionEstablishmentResponse rsp.UPFSEID.Seid [%v] ", rsp.UPFSEID.Seid)
Fix the warning coming out of GitHub Actions.

2023-01-05 14:22 UTC, ajaythakurintel approved these changes

2023-01-05 16:30 UTC, thakurajayL approved these changes

2023-01-05 16:34 UTC, merged