SMF failure handling
omec-project/smf pull request #129
Opened 2022-11-25 14:22 UTC by vthiruveedula

Pronto-133: SMF is not forwarding/sending PDU Session Establishment Reject to AMF

2022-11-29 04:29 UTC, thakurajayL requested changes

2022-12-20 07:35 UTC, UpadhyayaAnkur commented on context/db.go
>  	fmt.Println("db - in GetSMContextByRefInDB")
Please replace fmt.Println with smf log and ref printed in it.

2022-12-20 07:39 UTC, UpadhyayaAnkur commented on context/db.go
>  	smContext.SMLock.Lock()
Probably, taking this lock is not required. Lets discuss this

2022-12-20 07:41 UTC, UpadhyayaAnkur commented on context/sm_context.go
> +			smContext, _ := GetSMContextByRefInDB(ref)
Error added in return of GetSMContextByRefInDB() but not used

2023-01-03 10:02 UTC, UpadhyayaAnkur commented on context/db.go
> +		logger.CtxLog.Debugf("StoreSeidContextInDB, result string : ", ref)
Format specifier missing in log

2023-01-04 10:58 UTC, UpadhyayaAnkur approved these changes

2023-01-05 16:31 UTC, thakurajayL submitted a review, later dismissed

2023-01-06 05:53 UTC, UpadhyayaAnkur approved these changes

2023-01-06 05:59 UTC, merged