Fix non-functional linting warnings
omec-project/smf pull request #183
Opened 2023-11-08 14:08 UTC by gatici

Fixing whitespace and import order warnings by running following command. There is no functional change in the code.
```
golangci-lint run --fix
```

2023-11-22 01:42 UTC, gab-arrobo commented
retest this please

2023-11-23 14:28 UTC, thakurajayL commented
Do you need this to be reviewed ?

2023-11-24 15:37 UTC, gab-arrobo commented
test this please

2023-11-25 03:22 UTC, gab-arrobo commented
retest this please

2023-11-25 03:35 UTC, gab-arrobo commented
@gatici, I know why the `pull_request` fails and you have a PR that address the `unit-test-pfcpiface` (#180), but I was expecting this PR to pass the `golangci-lint` test/GHA. Am I overlooking something?

2023-11-29 19:39 UTC, gab-arrobo commented on context/sm_context.go
> +	"net"
```suggestion
```

2023-11-29 19:39 UTC, gab-arrobo commented on context/sm_context.go
> +	"net/http"
```suggestion
```

2023-11-29 19:40 UTC, gab-arrobo commented
> @gatici, I know why the `pull_request` fails and you have a PR that addresses the `unit-test-pfcpiface` (#180), but I was expecting this PR to pass the `golangci-lint` test/GHA. Am I overlooking something?

@gatici, please double check this PR because it like `golangci-lint run --fix` did not properly fix linting warnings and actually added more issues. For example, in context/sm_contest.go, imports are now duplicated as shown below:
```
	"net"
	"net/http"
	"net"
	"net/http"
```
I am making a couple modifications to see if the issue can be directly addressed from the PR

2023-11-29 19:41 UTC, gab-arrobo commented
test this please

2023-11-29 20:03 UTC, gab-arrobo requested changes

2023-11-29 20:03 UTC, gab-arrobo commented on consumer/nnrf.go
> +	param *Nnrf_NFDiscovery.SearchNFInstancesParamOpts,
Why is this comma `,` added in here?

2023-11-29 20:15 UTC, gab-arrobo commented
> Fixing whitespace and import order warnings by running following command. This PR does not affect the code functionality.
> 
> ```
> golangci-lint run --fix
> ```

@gatici, how did you install `golangci-lint`? I installed it through snap and from go but, through neither of these two options, I cannot replicate your PR by running `golangci-lint run --fix`

2023-12-01 19:25 UTC, gab-arrobo commented
> > golangci-lint
> 
> Hi @gab-arrobo I installed it through the [link](https://golangci-lint.run/usage/install/#binaries) by getting the binary, then run the command `golangci-lint run --fix`.

Hi @gatici, thanks for the link. Based on what I am reading, `golangci-lint` is the same as this [golangci-lint-action](https://github.com/golangci/golangci-lint-action) GHA, which is the recommended option for CI/CD projects as indicated [here](https://golangci-lint.run/usage/install/#github-actions). So, I am running the GitHub Action but it does not make any fixes/changes to the files. Would it be that your PR includes lots of changes because the way you are running the command (`golangci-lint run --fix`) and this does not take into account the options provided in [.golangci.yml](https://github.com/omec-project/smf/blob/master/.golangci.yml).

Moreover, when downloading the binary from the link you provided, I still cannot replicate your PR. Here are the steps I followed:

```
$ curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
$ golangci-lint --version
golangci-lint has version 1.55.2 built with go1.21.3 from e3c2265f on 2023-11-03T12:59:25Z
$ cd smf/
$ golangci-lint run --fix
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

2023-12-04 07:54 UTC, gatici commented
Hello  @gab-arrobo 

After rebasing on master, I can not reproduce it. The reason is https://github.com/omec-project/smf/pull/182/files# is disabled all the linters in .golangci.yml. After merging PR 182, this PR become invalid. I will close it at the moment.

2023-12-04 07:54 UTC, closed without merging